#!/usr/bin/env bash
# Timestamp: Sat Jun 17 14:08:56 UTC 2017
set -ex

nix-channel --add https://nix.dapphub.com/pkgs/dapphub
nix-channel --update

export NIX_PATH=/nix/var/nix/profiles/per-user/`whoami`/channels

path=$(nix-build '<dapphub>' -A dapp)
nix-push --dest nix-cache "$path"
