#!/usr/bin/env bash
set -ex

nix-channel --add https://nix.dapphub.com/pkgs/dapphub-staging dapphub
nix-channel --update

export NIX_PATH=/nix/var/nix/profiles/per-user/`whoami`/channels

path=$(nix-build '<dapphub>' -A dapp)
nix-push --dest nix-cache "$path"
